from .BaseView import BaseView
from .PINView import PINView
from .WelcomeView import WelcomeView
from .SelectTransactionView import SelectTransactionView
from .BalanceView import BalanceView
from .BalancePrintingView import BalancePrintingView
from .IncorrectPINView import IncorrectPINView
from .DepositView import DepositView
from .MalfunctionView import MalfunctionView
from .InsertDepositView import InsertDepositView